[package]
name = 'CoinList'
version = '0.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'e1c6a5713301ed72bf3a846ab9536d002ac801d6'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
coin_list = "0x91f6206a9ee4f969adf1e987b11a6a7ff4848fdb63b90f05ecd8a1a73b0e3efa"
